title: Quasar Framework
subtitle: "A fast, simple & powerful framework to simultaneously build websites and phone/tablet apps."
description: "Quasar is a fast, simple & powerful framework to simultaneously build websites and phone/tablet apps"
author: Razvan Stoenescu
language:
timezone: UTC

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://quasar-framework.org
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
archive_dir: news
code_dir: downloads/code
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true

default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false

relative_link: false
future: true

search:
  path: search.xml
  field: all

markdown:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true

highlight:
  enable: true
  line_number: false
  tab_replace:

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
per_page: 0
pagination_dir: page

# Extensions
theme: quasar

# Accounts
github: https://github.com/rstoenescu/quasar-framework
twitter: quasarframework
google_analytics: UA-6317975-4

# Deployment
deploy:
  type: git
  repo: git@github.com:rstoenescu/quasar-framework.git
  branch: gh-pages

sitemap:
    path: sitemap.xml
